
import javax.swing.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author Ignacio
 */
public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        InfoElem = new javax.swing.JLabel();
        TextoAsig = new javax.swing.JTextField();
        ComboAsig = new javax.swing.JComboBox<>();
        BotonAñadir = new javax.swing.JButton();
        BotonAñadirTodo = new javax.swing.JButton();
        BotonBorrarTodos = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Agregar Elementos Combox");

        InfoElem.setText("Añade el nombre de los modulos de los que estés matriculado:");

        ComboAsig.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboAsigActionPerformed(evt);
            }
        });

        BotonAñadir.setText("Añadir");
        BotonAñadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonAñadirActionPerformed(evt);
            }
        });

        BotonAñadirTodo.setText("Añadir Todos");
        BotonAñadirTodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonAñadirTodoActionPerformed(evt);
            }
        });

        BotonBorrarTodos.setText("Borrar Todos");
        BotonBorrarTodos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonBorrarTodosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(InfoElem)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TextoAsig, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BotonAñadir))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ComboAsig, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(BotonBorrarTodos, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(BotonAñadirTodo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(InfoElem)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TextoAsig, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ComboAsig, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BotonAñadir)
                    .addComponent(BotonAñadirTodo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BotonBorrarTodos)
                .addContainerGap(125, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BotonAñadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonAñadirActionPerformed
        // TODO add your handling code here:
        String asig = TextoAsig.getText().trim();

        if (!asig.isEmpty()) {
            boolean existe = false;

            for (int i = 0; i < ComboAsig.getItemCount(); i++) {
                String item = ComboAsig.getItemAt(i);

                if (item.equals(asig)) {
                    existe = true;
                    break;
                }
            }

            if (!existe) {
                ComboAsig.addItem(asig);
                TextoAsig.setText("");
            } else {
                JOptionPane.showMessageDialog(null, "Este elemento ya esta dentro del combobox");
            }
        } else {
            JOptionPane.showMessageDialog(null, "El campo de texto se encuentra vacio");
        }
    }//GEN-LAST:event_BotonAñadirActionPerformed

    private void ComboAsigActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboAsigActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComboAsigActionPerformed

    private void BotonAñadirTodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonAñadirTodoActionPerformed
        // TODO add your handling code here:
        String[] modulos = {"Programación multimedia", "Sistemas informáticos", "Bases de datos", "Lenguaje de marcas"};
        for (String modulo : modulos) {
            boolean existe = false;
            for (int i = 0; i < ComboAsig.getItemCount(); i++) {
                if (ComboAsig.getItemAt(i).equals(modulo)) {
                    existe = true;
                    break;
                }
            }
            if (!existe) {
                ComboAsig.addItem(modulo);
            }
        }
    }//GEN-LAST:event_BotonAñadirTodoActionPerformed

    private void BotonBorrarTodosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonBorrarTodosActionPerformed
        // TODO add your handling code here:
        ComboAsig.removeAllItems();
    }//GEN-LAST:event_BotonBorrarTodosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (UIManager.LookAndFeelInfo info : UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    UIManager.setLookAndFeel(info.getClassName());
                    System.out.println("Look and Feel de Windows aplicado correctamente.");
                    break;
                }
            }
        } catch (Exception ex) {
            ex.printStackTrace();
            System.out.println("Error al aplicar el Look and Feel de Windows.");
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonAñadir;
    private javax.swing.JButton BotonAñadirTodo;
    private javax.swing.JButton BotonBorrarTodos;
    private javax.swing.JComboBox<String> ComboAsig;
    private javax.swing.JLabel InfoElem;
    private javax.swing.JTextField TextoAsig;
    // End of variables declaration//GEN-END:variables
}
